using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Management.Models
{
    public class Venta
    {
        //preguntar ICCID y OperadorDonante se repiten en el join
        public string LastInteractionId { get; set; }
        public string VCC { get; set; }
        public string CampaignId { get; set; }
        public string LastAgent { get; set; }
        public string ContactAddress { get; set; }
        public DateTime TmStmp { get; set; }
        public string OutboundProcessId { get; set; }
        public string BatchId { get; set; }
        public string ContactId { get; set; }
        public string ContactName { get; set; }
        public string Nivel1 { get; set; }
        public string Nivel2 { get; set; }
        public string Nivel3 { get; set; }
        public string ManagementResultCode { get; set; }
        public string ManagementResultDescription { get; set; }
        public string schedule { get; set; }
        public string RescheduledToPhone { get; set; }
        public string RescheduledToPhoneType { get; set; }
        public DateTime? RescheduledToDate { get; set; }
        public string RescheduledToTime { get; set; }
        public string RescheduledToAgent { get; set; }
        public string RescheduledToCampaign { get; set; }
        public string RescheduledAgentIsSame { get; set; }
        public string Observaciones { get; set; }
        public string TipoVenta { get; set; }
        public string Convergente { get; set; }
        public string NombresCompletos { get; set; }
        public string TipoDocumento { get; set; }
        public string NumeroDocumento { get; set; }
        public string FechaExpedicion { get; set; }
        public string CorreoElectronico { get; set; }
        public string FacturaCorreo { get; set; }
        public string Departamento { get; set; }
        public string Ciudad { get; set; }
        public string Barrio { get; set; }
        public string Estrato { get; set; }
        public string Correspondencia { get; set; }
        public string DireccionCorrespondencia { get; set; }
        public string Telefono { get; set; }
        public string Celular { get; set; }
        public string ObservacionesDireccion { get; set; }
        public string Franja { get; set; }
        public string TipoPlan { get; set; }
        public string PrimerApellido { get; set; }
        public string Sexo { get; set; }
        public string IdTelemercadeo { get; set; }
        public string DominioCorreo { get; set; }
        public string FechaNacimiento { get; set; }
        public string Complemento { get; set; }
        public string OtroDominio { get; set; }
        public string Aplicativo { get; set; }
        public string TelefonoContrato { get; set; }
        public string FechaContrato { get; set; }
        public string HoraGrabacion { get; set; }
        public string Segmento { get; set; }
        public string Politica { get; set; }
        public string CodigoCampana { get; set; }
        public string CodigoEvidente { get; set; }
        public string DireccionInstalacion { get; set; }
        public string RentaMensual { get; set; }
        public string Refiere { get; set; }
        public string Television { get; set; }
        public string Internet { get; set; }
        public string Voz { get; set; }
        public string TomasAdicionales { get; set; }
        public string DecosAdicionales { get; set; }
        public string Adicionales1 { get; set; }
        public string Adicionales2 { get; set; }
        public string Adicionales3 { get; set; }
        public string Adicionales4 { get; set; }
        public string Upgrades { get; set; }
        public string CelularGestionar { get; set; }
        public string PlanSolicitado { get; set; }
        public string PlanActual { get; set; }
        public string DispositivoMovil { get; set; }
        public string Tipo { get; set; }
        public string ICCID { get; set; }
        public string ZonaVenta { get; set; }
        public string TipoCredito { get; set; }
        public string Comportamiento { get; set; }
        public string CampanaOfrecida { get; set; }
        public string NumeroCaso { get; set; }
        public string OperadorDonante { get; set; }
        public string Nip { get; set; }
        public string CargoFijo { get; set; }
        public string ArchivoFija { get; set; }
        public string Referencia1 { get; set; }
        public string TipoContactoReferencia1 { get; set; }
        public string IndicativoReferencia1 { get; set; }
        public string NumeroSinIndicativosReferencia1 { get; set; }
        public string SegundoContacto { get; set; }
        public string PersonaAutoriza { get; set; }
        public string DepartamentoEntrega { get; set; }
        public string CiudadEntrega { get; set; }
        public string FechaAgendamientoOperador { get; set; }
        public string FranjaEntrega { get; set; }
        public string ExisteCentroAcopio { get; set; }
        public string DatosAdicionales { get; set; }
        public string DireccionEntrega { get; set; }
        public string BarrioEntrega { get; set; }
        public string CentroAcopio { get; set; }
        public string ObservacionesEntrega { get; set; }
        public int? IdEstadoVenta { get; set; }
        public string SubEstado { get; set; }
        public string ID { get; set; }
        public string SKILL { get; set; }
        public string TIPO_DE_BBDD { get; set; }
        public string TELE_NUMB { get; set; }
        public string CO_ID { get; set; }
        public string RANGO_VLRCARG { get; set; }
        public string NOMBRE_CLIENTE { get; set; }
        public string IDENTIFICACION { get; set; }
        public string ICCID_Cliente { get; set; }
        public string REGION_UBICACION { get; set; }
        public string DEPARTAMENTO_UBICACION { get; set; }
        public string MUNICIPIO_UBICACION { get; set; }
        public string CLIENTE_HOGAR { get; set; }
        public string CALLING_NUMBER { get; set; }
        public string CIUDAD { get; set; }
        public string NVA_REGION { get; set; }
        public string RECEPTOR { get; set; }
        public string TEL1_HOG { get; set; }
        public string TEL2_HOG { get; set; }
        public string ESTRATO { get; set; }
        public string CUPO_CARTERA { get; set; }
        public string CUENTA { get; set; }
        public string ESTADO_DEL_CONTACTO_EN_CLARO { get; set; }
        public string APELLIDO { get; set; }
        public string NOMBRE { get; set; }
        public string TIPO_IDENT { get; set; }
        public string TIPO_LINEA { get; set; }
        public string TELE_NUMB_PREPAGO { get; set; }
        public string RANGO_RECARGA { get; set; }
        public string TELEFONO_1 { get; set; }
        public string TELEFONO_2 { get; set; }
        public string TELEFONO_3 { get; set; }
        public string CELULAR_1 { get; set; }
        public string TIPO_LINEA_CONTACTO_1 { get; set; }
        public string RANGO_RECARGA_CONTACTO_1 { get; set; }
        public string CELULAR_2 { get; set; }
        public string TIPO_LINEA_CONTACTO_2 { get; set; }
        public string RANGO_RECARGA_CONTACTO_2 { get; set; }
        public string CELULAR_3 { get; set; }
        public string TIPO_LINEA_CONTACTO_3 { get; set; }
        public string RANGO_RECARGA_CONTACTO_3 { get; set; }
        public string DIRECCION { get; set; }
        public string RENTA { get; set; }
        public string SERVICIO_TV { get; set; }
        public string SERVICIO_INTERNET { get; set; }
        public string SERVICIO_VOZ { get; set; }
        public string TIPO_HD { get; set; }
        public string TIPO_HBO { get; set; }
        public string TIPO_FOX { get; set; }
        public string TIPO_ADULTO { get; set; }
        public string NUM_DECOS_ADI { get; set; }
        public string TIPO_CLAROVIDEO { get; set; }
        public string TIPO_OTROS { get; set; }
        public string DIVISION_COMERCIAL { get; set; }
        public string PAQUETE { get; set; }
        public string TELEFONO_TELMEX { get; set; }
        public string RENTA_BASICOS { get; set; }
        public string RENTA_ADICIONALES { get; set; }
        public string RENTA_TOTAL_IVA { get; set; }
        public string MINTIC { get; set; }
        public string CAMPANA_INCONCERT { get; set; }
        public string CAMPANA_GSS { get; set; }
        public string ANIO { get; set; }
        public string MES { get; set; }
        public string BASE { get; set; }
        public string Validador { get; set; }
        public int? IdSubEstadoVenta { get; set; }
        public string ObservacionesValidador { get; set; }
        public DateTime? FechaValidacion { get; set; }
        public string CodigoTMK { get; set; }
        public string EstadoVenta { get; set; }
        public string SubEstadoVenta { get; set; }
        public string NombreCoordinador { get; set; }
        public string DescripcionSubEstado { get; set; }
        //nuevos campos
        public string NumeroContrato { get; set; }
        public string NumeroRegistro { get; set; }
        public DateTime? FechaInstalacion { get; set; }
        public string RangoInstalacionInicial { get; set; }
        public string RangoInstalacionFinal { get; set; }
        public string OrdenTrabajo { get; set; }
        public string Suscriptor { get; set; }
        public string IDUltimo { get; set; }
        public string CantidadServicios { get; set; }
        public DateTime? FechaActivacionAc { get; set; }
        public string Cutscode { get; set; }
        public string EstadoICCID { get; set; }
        public string SubEstadoPortabilidad { get; set; }
        public DateTime? FechaEnvioABD { get; set; }
        public string Razon { get; set; }
        public string NumeroCuotas { get; set; }
        public string ReferenciaEquipo { get; set; }
        public string ValorEquipo { get; set; }
        public string Reserva { get; set; }
        public DateTime? FechaDigitacion { get; set; }
        public long? IdClienteClaro { get; set; }
        public string ClienteClaro { get; set; }
        public string VentaTecnologia { get; set; }
        public string VentaTerminales { get; set; }
        public Decimal? ValorConIvaTecnologia { get; set; }
        public string NumeroReservaTecnologia { get; set; }
        public Decimal? ValorSinIvaTecnologia { get; set; }
        public string DireccionEntregaTecnologia { get; set; }
        public string NumeroCuotasTecnologia { get; set; }
        public string TelefonoContactoTecnologia { get; set; }
        public string NumeroRadicadoTecnologia { get; set; }
        public string ObservacionesTecnologia { get; set; }
        public Decimal? ValorConIvaTerminales { get; set; }
        public string NumeroReservaTerminales { get; set; }
        public Decimal? ValorSinIvaTerminales { get; set; }
        public string DireccionEntregaTerminales { get; set; }
        public string NumeroCuotasTerminales { get; set; }
        public string TelefonoContactoTerminales { get; set; }
        public string NumeroRadicadoTerminales { get; set; }
        public string ObservacionesTerminales { get; set; }
        public string UltraWifi { get; set; }
        public string AliadoInstalador { get; set; }
        public string OpcionInternet { get; set; }
        public string OpcionTelevision { get; set; }
        public string Nodo { get; set; }
        public DateTime? FechaDeInstalacion { get; set; }
        public string FechaDeInstalacion1 { get; set; }
        public string ObservacionesInstalador { get; set; }
        public string Radicado { get; set; }
        public string Material { get; set; }

    }
}
